const stories = [
    // ================= EASY (10 ТЕКСТОВ) =================
    { 
        title: "The Life of a Garden", cat: "Nature", lvl: "Easy", 
        text: "A garden is a very busy place. In the spring, the sun warms the soil, and small green plants begin to grow. You can see colorful flowers like red roses and yellow sunflowers. Bees fly from flower to flower to collect sweet nectar.\n\nButterflies also love the garden. They have beautiful wings with many patterns. Digging in the dirt, you might find earthworms. Earthworms are good for the garden because they help the air reach the roots of the plants.\n\nWatering the garden is important. Plants need water to stay strong when the weather is hot. If you take good care of your garden, it will be a beautiful place for birds and insects to live all summer long." 
    },
    { 
        title: "My Trip to the Zoo", cat: "Animals", lvl: "Easy", 
        text: "Last Saturday, my family went to the big city zoo. The first animals we saw were the tall giraffes. They have very long necks so they can eat leaves from the tops of the trees. Their tongues are dark blue and very strong.\n\nNext, we visited the elephant area. Elephants are the largest land animals. They use their long trunks to drink water and pick up food. We saw a baby elephant playing in the mud with its mother. It was very funny to watch.\n\nBefore we left, we saw the lions. The male lion has a big mane around his head. He was sleeping in the sun, but he looked very powerful. The zoo is a great place to learn about animals from all over the world." 
    },
    { 
        title: "The Moon in the Night Sky", cat: "Space", lvl: "Easy", 
        text: "When the sun goes down, the moon appears in the sky. The moon does not have its own light. It shines because it reflects the light from the sun. Sometimes the moon looks like a big white circle, and sometimes it looks like a thin banana.\n\nThe moon is much smaller than the Earth. It moves around our planet in a big circle. Long ago, in 1969, the first humans traveled in a rocket and walked on the moon. They had to wear special suits because there is no air to breathe there.\n\nLooking at the moon through a telescope is fun. You can see big holes called craters. These holes were made by rocks hitting the moon a long time ago. The moon is our closest neighbor in space." 
    },
    { 
        title: "A Day at the Beach", cat: "Life", lvl: "Easy", 
        text: "The beach is a wonderful place to visit in the summer. You can feel the warm sand between your toes and hear the sound of the blue waves hitting the shore. Many people like to swim in the cool water or jump over the waves.\n\nChildren often build sandcastles using buckets and shovels. They look for pretty seashells and small crabs near the rocks. It is important to wear sunscreen and a hat so the sun does not burn your skin.\n\nIn the afternoon, you can have a picnic. Sandwiches and fruit taste better at the beach! When the sun starts to set, the sky turns orange and pink. The beach is a perfect place to relax and have fun with your friends." 
    },
    { 
        title: "The Seasons of the Year", cat: "Nature", lvl: "Easy", 
        text: "There are four seasons: spring, summer, autumn, and winter. In spring, the trees get new leaves and the birds sing. It is a time for new beginnings. Summer is the hottest season, with long days and lots of sunshine.\n\nIn autumn, the weather gets cooler. The leaves turn orange and brown before they fall to the ground. Farmers harvest their crops like apples and pumpkins. It is a very colorful time of the year.\n\nWinter is the coldest season. In some places, it snows, and everything looks white. People wear warm coats, scarves, and gloves. We celebrate holidays and drink hot chocolate. Each season is special and brings different things to enjoy." 
    },
    { 
        title: "Learning to Ride a Bike", cat: "Life", lvl: "Easy", 
        text: "Learning to ride a bicycle is an exciting adventure. First, you might use training wheels to help you keep your balance. You sit on the seat, put your feet on the pedals, and hold the handlebars tightly.\n\nWhen you are ready, your father or mother takes off the training wheels. They might hold the back of your bike while you start to pedal. You have to look straight ahead and keep pedaling fast. If you stop, the bike might tip over!\n\nIt is okay to fall down sometimes. You just have to get up and try again. Don't forget to wear your helmet to keep your head safe. Soon, you will be able to ride all by yourself down the street." 
    },
    { 
        title: "How to Make a Sandwich", cat: "Cooking", lvl: "Easy", 
        text: "Making a sandwich is a great way to fix a quick lunch. First, you need two slices of fresh bread. You can use white bread or brown bread. You also need some butter or mayonnaise to spread on the bread.\n\nNext, choose what you want to put inside. Many people like cheese, ham, or turkey. You can also add vegetables like lettuce, red tomatoes, and cucumbers. These make the sandwich healthy and crunchy.\n\nPut the two slices together and cut the sandwich in half. Now it is ready to eat! You can have your sandwich with an apple or some chips. It is simple, fast, and very delicious." 
    },
    { 
        title: "The Helpful Robot", cat: "Tech", lvl: "Easy", 
        text: "In the future, many people will have robots in their homes. A robot is a machine that can follow instructions. Some robots look like humans, and some look like small boxes with wheels.\n\nA helpful robot can do chores for you. It can vacuum the floor, wash the dishes, and even tidy up your toys. This gives people more time to play and study. Robots don't get tired and they never complain about work.\n\nTo make a robot work, you need to give it a battery and a computer brain. Scientists are working hard to make robots smarter every day. Maybe one day, you will have a robot friend to help you with your homework!" 
    },
    { 
        title: "Our Five Senses", cat: "Science", lvl: "Easy", 
        text: "We use our five senses to understand the world around us. These senses are sight, hearing, smell, taste, and touch. We use our eyes to see colors and shapes. We use our ears to hear music and voices.\n\nOur nose helps us smell flowers and delicious food. Our tongue lets us taste if something is sweet, salty, or sour. Finally, our skin allows us to touch and feel if something is hot, cold, soft, or hard.\n\nAll of these senses send messages to our brain. Our brain tells us what is happening and keeps us safe. Using all five senses makes life very interesting and full of discoveries." 
    },
    { 
        title: "The Friendly Dog", cat: "Animals", lvl: "Easy", 
        text: "A dog is often called 'man's best friend.' Dogs are very loyal and love to spend time with people. They come in many sizes, from very small to very large. Some have long fur, and some have short fur.\n\nDogs need a lot of care. You must take them for a walk every day so they can get exercise. They also need good food and fresh water. Most dogs love to play with a ball or a stick in the park.\n\nWhen a dog is happy, it wags its tail. When it wants to say hello, it might bark. Training a dog is important so it knows how to behave. If you are kind to a dog, it will love you forever." 
    },

    // ================= MEDIUM (10 ТЕКСТОВ) =================
    { 
        title: "The Great Wall of China", cat: "History", lvl: "Medium", 
        text: "The Great Wall of China is one of the most impressive architectural feats in human history. Stretching over 21,000 kilometers, it was built over many centuries by various Chinese dynasties. Its primary purpose was to protect the empire from invasions.\n\nConstructing the wall was a massive task that required millions of workers. They used stone, brick, wood, and even earth to build the structure. In some places, the wall is high enough and wide enough for several horses to run along the top together.\n\nToday, the Great Wall is a UNESCO World Heritage site and a symbol of China's long history. Millions of tourists visit different sections of the wall every year. It serves as a reminder of the strength and determination of the ancient Chinese people." 
    },
    { 
        title: "How Volcanos Work", cat: "Geography", lvl: "Medium", 
        text: "A volcano is a mountain that opens downward to a pool of molten rock below the surface of the earth. When pressure builds up, eruptions occur. During an eruption, gases and rock shoot up through the opening and spill over the top.\n\nThere are three main types of volcanoes: active, dormant, and extinct. An active volcano is one that has erupted recently or is expected to erupt soon. A dormant volcano is like a sleeping giant; it hasn't erupted for a long time but could wake up.\n\nVolcanic eruptions can be very dangerous, but they also create new land. Many islands, like Hawaii and Iceland, were formed by volcanic activity. The ash from volcanoes also makes the soil very fertile, which is great for growing crops." 
    },
    { 
        title: "The Smartest Ocean Animals", cat: "Animals", lvl: "Medium", 
        text: "Dolphins are widely considered to be some of the smartest animals on the planet. They live in social groups called pods and communicate with each other using a complex system of whistles and clicks. They even have 'signature whistles' that act like names.\n\nResearch has shown that dolphins are capable of self-awareness, meaning they can recognize themselves in a mirror. They are also very cooperative, often working together to herd fish into a tight circle so they can eat more easily.\n\nBesides dolphins, the octopus is another highly intelligent sea creature. They can solve puzzles and use tools. Both animals show us that intelligence is not limited to land-dwelling creatures. The ocean is full of brilliant minds that we are still trying to understand." 
    },
    { 
        title: "The History of the Olympic Games", cat: "History", lvl: "Medium", 
        text: "The Olympic Games began in ancient Greece over 2,700 years ago. They were held in honor of Zeus, the king of the gods. At that time, only men could compete, and the winners were given olive leaf crowns and treated like heroes.\n\nThe modern Olympic Games started in 1896 in Athens. Since then, they have grown into the world's largest sporting event. Every four years, athletes from almost every country gather to compete in hundreds of different events, from running to swimming.\n\nThe goal of the Olympics is to promote peace and friendship between nations through sports. The five rings on the Olympic flag represent the five major continents of the world. It is a time when the whole world comes together to celebrate human achievement." 
    },
    { 
        title: "How Electricity Reaches Your Home", cat: "Science", lvl: "Medium", 
        text: "Have you ever wondered how the lights turn on when you flip a switch? It all starts at a power plant. Electricity can be generated from many sources, such as burning coal, using flowing water in a dam, or catching the wind with giant turbines.\n\nOnce the electricity is created, it travels through thick wires to a transformer. The transformer increases the voltage so the electricity can travel long distances through high-voltage power lines. These lines are the big wires you see held up by tall metal towers.\n\nFinally, the electricity reaches your neighborhood. Another transformer lowers the voltage to make it safe for your house. It travels through smaller wires into your walls and right to your plugs. It is a long and fast journey that happens in a split second!" 
    },
    { 
        title: "The Mystery of the Titanic", cat: "History", lvl: "Medium", 
        text: "The Titanic was the largest and most luxurious ship of its time. It was called 'unsinkable' because of its advanced design. In April 1912, it set sail from England to New York on its very first voyage with over 2,000 people on board.\n\nUnfortunately, on the night of April 14, the ship hit a massive iceberg in the North Atlantic Ocean. The iceberg tore a hole in the side of the ship, and water began to pour in. Because there were not enough lifeboats for everyone, more than 1,500 people lost their lives.\n\nThe story of the Titanic remains famous today. In 1985, the wreck was discovered on the ocean floor, 4 kilometers underwater. Scientists continue to study the ship to learn more about exactly what happened on that tragic night." 
    },
    { 
        title: "Why Do We Dream?", cat: "Psychology", lvl: "Medium", 
        text: "Every night, when we go to sleep, our brains stay active and create stories called dreams. Sometimes dreams are happy and exciting, and other times they can be scary or very strange. But why exactly do we dream?\n\nSome scientists believe that dreaming helps the brain process the information and emotions we experienced during the day. It's like a cleaning service for your mind, deciding what memories to keep and what to throw away. Other researchers think dreams are a way for us to practice dealing with problems.\n\nMost dreaming happens during a stage of sleep called REM (Rapid Eye Movement). During this time, your body is very still, but your brain is working hard. Even if you don't remember your dreams in the morning, you probably had several during the night!" 
    },
    { 
        title: "The Importance of Recycling", cat: "Nature", lvl: "Medium", 
        text: "Recycling is the process of collecting and processing materials that would otherwise be thrown away as trash and turning them into new products. This is very important for protecting our environment and saving natural resources.\n\nWhen we recycle paper, we save trees. When we recycle plastic and metal, we use less energy than making those items from scratch. It also reduces the amount of waste that goes into landfills, which are big holes in the ground where trash is buried.\n\nMost cities have special bins for paper, plastic, glass, and aluminum. By taking a few minutes to sort your trash, you are helping to keep the planet clean. Small actions by many people can make a huge difference for the Earth's future." 
    },
    { 
        title: "The World of Virtual Reality", cat: "Tech", lvl: "Medium", 
        text: "Virtual Reality, or VR, is a technology that uses a special headset to create a computer-generated world. When you put on the headset, it looks like you are inside a different place, even though you are just standing in your room.\n\nVR is most famous for video games, but it is also used for many other things. Doctors use it to practice surgeries before they work on real patients. Pilots use VR flight simulators to learn how to fly airplanes safely without leaving the ground.\n\nAs the technology gets better, VR will become even more realistic. You might one day take a virtual field trip to the bottom of the ocean or the surface of Mars. It is a powerful tool that changes how we learn and play." 
    },
    { 
        title: "The Life of a Star", cat: "Space", lvl: "Medium", 
        text: "Stars are not eternal; they are born, they live for billions of years, and eventually, they die. A star begins its life inside a giant cloud of gas and dust called a nebula. Gravity pulls the gas together until it gets so hot that it starts to shine.\n\nOur sun is a middle-aged star. It has been shining for 5 billion years and will likely continue for another 5 billion. Larger stars burn through their fuel much faster than smaller stars. When a very large star dies, it can explode in a massive event called a supernova.\n\nAfter the explosion, the remains of the star might become a tiny, dense neutron star or even a black hole. The dust from the explosion eventually forms new nebulae, where new stars can be born. It is a grand cycle that has been happening since the beginning of the universe." 
    },

    // ================= HARD (10 ТЕКСТОВ) =================
    { 
        title: "The Theory of General Relativity", cat: "Science", lvl: "Hard", 
        text: "In 1915, Albert Einstein published his theory of general relativity, which fundamentally transformed our understanding of space, time, and gravity. Before Einstein, gravity was seen as a force between objects. Einstein proposed something far more revolutionary.\n\nHe suggested that space and time are linked together in a four-dimensional fabric called spacetime. Massive objects, like stars and planets, do not just pull on things; they actually warp and curve the fabric of spacetime itself. Think of a heavy ball sitting on a trampoline.\n\nThis curvature tells objects how to move. This theory explained why light bends when it passes near a sun and predicted the existence of black holes. Today, general relativity is essential for the technology in our smartphones; without it, GPS systems would be inaccurate by several kilometers every day." 
    },
    { 
        title: "The Microbiome Within Us", cat: "Medicine", lvl: "Hard", 
        text: "You are not just a single organism; you are a walking ecosystem. The human body is home to trillions of microorganisms, including bacteria, fungi, and viruses. Collectively, these are known as the human microbiome, and they play a critical role in our health.\n\nMost of these microbes live in your digestive system. They help break down food that your body cannot digest on its own and produce essential vitamins. Recent research suggests that the microbiome also communicates with the brain, influencing our mood and mental health.\n\nAn imbalance in this delicate ecosystem has been linked to various diseases, such as obesity and autoimmune disorders. Maintaining a healthy microbiome through a balanced diet rich in fiber and fermented foods is becoming a major focus of modern medicine. We are only beginning to understand the complexity of our relationship with these tiny residents." 
    },
    { 
        title: "The Great Depression", cat: "History", lvl: "Hard", 
        text: "The Great Depression was a severe worldwide economic downturn that took place mostly during the 1930s. It began in the United States after a major fall in stock market prices in October 1929, an event known as Black Tuesday. The impact was felt globally, from industrial cities to rural farming communities.\n\nDuring this period, unemployment reached record levels, and millions of people lost their homes and savings. International trade plummeted, and many banks failed, leaving people with no way to access their money. In many countries, bread lines and soup kitchens became common sights as families struggled to survive.\n\nRecovery was slow and required massive government intervention. In the US, President Franklin D. Roosevelt introduced the New Deal, a series of programs designed to provide relief and reform the financial system. The depression finally ended as countries shifted their economies toward military production at the start of World War II." 
    },
    { 
        title: "The Philosophy of Stoicism", cat: "Psychology", lvl: "Hard", 
        text: "Stoicism is an ancient Greek philosophy that has seen a resurgence in popularity in the modern era. It teaches that while we cannot control the external events that happen to us, we have total control over how we choose to respond to them. The goal is to achieve a state of inner peace and resilience.\n\nStoics believe that most human suffering comes from wanting things to be different than they are. By focusing only on what is within our 'sphere of choice'—our thoughts, intentions, and actions—we can remain calm even in the face of adversity. This does not mean being emotionless, but rather being rational and virtuous.\n\nKey figures like Marcus Aurelius and Seneca emphasized the importance of self-discipline and living in accordance with nature. Stoicism provides a practical toolkit for managing stress and making ethical decisions, reminding us that our character is the only thing that truly belongs to us." 
    },
    { 
        title: "Artificial Intelligence and the Turing Test", cat: "Tech", lvl: "Hard", 
        text: "The quest to create a machine that can think like a human began decades ago. In 1950, the mathematician Alan Turing proposed a way to measure a machine's intelligence, now known as the Turing Test. The test involves a human judge having a conversation with both a human and a computer.\n\nIf the judge cannot reliably tell which one is the computer based on the responses, the machine is said to have passed the test. For a long time, this was considered the ultimate goal of AI. However, as modern AI models become more sophisticated, the Turing Test is being re-evaluated.\n\nToday's AI can generate remarkably human-like text, but does that mean it actually 'understands' what it is saying? Many experts argue that true intelligence requires consciousness and lived experience, something a computer code currently lacks. The debate over whether a machine can ever truly 'think' remains one of the greatest challenges in computer science." 
    },
    { 
        title: "The Mysteries of Dark Matter", cat: "Space", lvl: "Hard", 
        text: "When astronomers look at the universe, they realize that everything we can see—stars, planets, and galaxies—makes up only about 5% of the total mass and energy of the cosmos. The rest is made of two mysterious substances: dark matter and dark energy. We cannot see them because they do not emit light.\n\nScientists know dark matter exists because of its gravitational effect on visible matter. Galaxies rotate much faster than they should based on the amount of visible stars they contain. Something invisible must be providing extra gravity to hold them together. This invisible 'glue' is what we call dark matter.\n\nDark energy, on the other hand, seems to be responsible for the accelerating expansion of the universe. It acts like a repulsive force that pushes galaxies away from each other. Understanding these two components is the biggest challenge in modern physics, as it would reveal the ultimate fate of our universe." 
    },
    { 
        title: "The Industrial Revolution's Impact", cat: "History", lvl: "Hard", 
        text: "The Industrial Revolution, which began in Britain in the late 1700s, was one of the most significant turning points in human history. It marked the transition from hand production methods to machines and the rise of the factory system. This shift led to an unprecedented increase in production and economic growth.\n\nHowever, the social consequences were complex. Rapid urbanization led to overcrowded and unsanitary living conditions in cities. Workers, including children, often endured long hours in dangerous environments for low wages. This eventually led to the birth of labor unions and new laws to protect workers' rights.\n\nTechnologically, the era gave us the steam engine, the telegraph, and the first locomotives. It fundamentally changed how people lived, worked, and traveled. The environmental legacy of the Industrial Revolution, particularly the increase in carbon emissions, is a challenge that we are still dealing with today in the 21st century." 
    },
    { 
        title: "Neuroplasticity: The Changing Brain", cat: "Science", lvl: "Hard", 
        text: "For many years, scientists believed that the adult brain was 'hard-wired' and could not change. We now know that this is incorrect. The brain possesses a remarkable quality called neuroplasticity, which is the ability to reorganize itself by forming new neural connections throughout life.\n\nNeuroplasticity allows the neurons in the brain to adjust their activities in response to new situations or changes in the environment. This is how we learn new skills, recover from brain injuries, and adapt to new languages. When you practice a skill, the connections between relevant neurons become stronger.\n\nThis discovery has huge implications for medicine and education. It means that with the right training and effort, we can improve our cognitive abilities at any age. It also offers hope for treating conditions like stroke or Alzheimer's, as researchers look for ways to stimulate the brain's natural ability to rewire itself." 
    },
    { 
        title: "The Evolution of Modern Medicine", cat: "Medicine", lvl: "Hard", 
        text: "Modern medicine has come a long way since the days when infections were treated with herbal charms or bloodletting. The 19th and 20th centuries saw a series of breakthroughs that doubled the average human lifespan. One of the most critical was the discovery of the 'germ theory' of disease.\n\nOnce scientists understood that microscopic organisms caused illness, they could develop vaccines and antibiotics. Penicillin, discovered by Alexander Fleming, saved millions of lives during World War II and beyond. The development of anesthesia also allowed for complex surgeries that were previously impossible due to the pain.\n\nToday, we are entering the era of personalized medicine. By sequencing a patient's DNA, doctors can tailor treatments to their specific genetic makeup. While we still face major challenges like cancer and antibiotic resistance, the pace of medical innovation continues to accelerate at a staggering rate." 
    },
    { 
        title: "The Architecture of the Renaissance", cat: "History", lvl: "Hard", 
        text: "Renaissance architecture, which began in Florence in the early 15th century, represented a conscious revival of the elements of classical Greek and Roman thought and material culture. Architects like Filippo Brunelleschi sought to move away from the complex Gothic style toward something more harmonious and symmetrical.\n\nThe use of the dome, the column, and the arch became central to this new style. One of the greatest examples is the Dome of the Florence Cathedral, a massive engineering feat that remains a symbol of human ingenuity. Renaissance buildings were designed to reflect the order and beauty of the natural world.\n\nThis movement was not just about aesthetics; it was deeply tied to the philosophy of humanism. Buildings were intended to be built on a human scale, emphasizing the importance of the individual's experience within the space. This period laid the groundwork for modern architectural principles and remains a source of inspiration for designers worldwide." 
    }
];

const stories2 = [
    // ================= EASY (10 ТЕКСТОВ) =================
    { 
        title: "The Story of King Midas", cat: "Mythology", lvl: "Easy", 
        text: "Long ago, there was a king named Midas who loved gold more than anything else in the world. One day, a god gave him a special wish. Midas wished that everything he touched would turn into shining gold.\n\nAt first, the king was very happy. He touched his flowers, his chair, and even his castle walls, and they all became gold. But then, he became hungry. When he tried to eat an apple, it turned into hard metal. When he tried to drink water, it became gold too.\n\nHe realized that his wish was actually a curse. He could not eat or drink, and he was very sad. Finally, the god took the power away. King Midas learned that there are many things in life more important than money and gold." 
    },
    { 
        title: "Albert Einstein: A Great Mind", cat: "Biographies", lvl: "Easy", 
        text: "Albert Einstein was one of the most famous scientists in history. He was born in Germany a long time ago. When he was a small boy, he did not talk much, and some people thought he was not very smart. But Albert loved to think about how the world works.\n\nHe spent a lot of time studying light and space. He discovered that time and space are connected. Because of his great ideas, he won the Nobel Prize in Physics. He became famous all over the world, but he remained a very simple and kind man.\n\nEinstein liked to play the violin and go sailing in his free time. He always encouraged children to ask questions and stay curious. His work changed science forever, and we still use his ideas today to understand the universe." 
    },
    { 
        title: "How to Start a Small Business", cat: "Business", lvl: "Easy", 
        text: "Do you want to start a business? It can be as simple as a lemonade stand or washing cars for your neighbors. First, you need an idea. Think about what people need and what you are good at doing.\n\nNext, you need a plan. You must decide how much money you need to buy supplies. For a lemonade stand, you need lemons, sugar, and cups. Then, you choose a good place to work where many people will see you.\n\nWhen you sell your product, you must be polite and smile at your customers. If you work hard and save your money, your small business can grow. Starting a business is a great way to learn about responsibility and how to handle money." 
    },
    { 
        title: "The Festival of Colors", cat: "Culture", lvl: "Easy", 
        text: "Holi is a very famous festival in India. It is often called the 'Festival of Colors'. It happens in the spring when the weather becomes warm. People celebrate the end of winter and the victory of good over evil.\n\nDuring Holi, people go out into the streets and throw colorful powder at each other. Everyone becomes red, green, blue, and yellow! They also use water balloons and spray guns to have fun. It is a time for singing, dancing, and laughing with friends.\n\nIn the evening, families visit each other and share special sweets. It is a day when everyone is equal and happy. Holi is a beautiful tradition that brings people together and fills the world with bright colors." 
    },
    { 
        title: "The Brave Firefighters", cat: "Life", lvl: "Easy", 
        text: "Firefighters are very brave people who help keep us safe. They work at a fire station and are always ready to go when the alarm rings. They wear special heavy coats, boots, and helmets to protect them from heat.\n\nWhen there is a fire, they drive a big red truck with loud sirens. They use long hoses to spray water on the flames. Firefighters also help people during car accidents and floods. They are trained to stay calm in dangerous situations.\n\nYou can visit a fire station to learn about fire safety. They will show you how to 'stop, drop, and roll' if your clothes catch fire. We should always be thankful for the hard work that firefighters do for our community." 
    },
    { 
        title: "Mount Everest: The Highest Peak", cat: "Geography", lvl: "Easy", 
        text: "Mount Everest is the highest mountain in the world. It is located in the Himalayas, between the countries of Nepal and China. It is so high that the top is always covered in snow and ice, even in the summer.\n\nClimbing Mount Everest is very difficult and dangerous. The air at the top is very thin, so climbers have to use oxygen tanks to breathe. It is also very cold, and the wind blows very hard. Many people dream of standing on the top of the world.\n\nThe first people to reach the top were Edmund Hillary and Tenzing Norgay in 1953. Today, many climbers try to follow their path. It takes a lot of training and courage to reach the highest point on Earth." 
    },
    { 
        title: "The Invention of the Telephone", cat: "Tech", lvl: "Easy", 
        text: "A long time ago, people could only send messages by letters. It took a long time for a letter to arrive. Then, a man named Alexander Graham Bell had a great idea. He wanted to send voices through wires.\n\nIn 1876, he invented the first telephone. The first words he said were, 'Mr. Watson, come here, I want to see you.' Mr. Watson was in another room and he heard Bell's voice perfectly. It was a miracle of technology!\n\nToday, we use smartphones that are much smaller and faster. We can call people on the other side of the world and even see their faces. But it all started with Bell's simple invention. The telephone changed how we talk to each other forever." 
    },
    { 
        title: "The Great Barrier Reef", cat: "Nature", lvl: "Easy", 
        text: "The Great Barrier Reef is the largest coral reef system in the world. It is located in the ocean near Australia. It is so big that you can even see it from space! It is made of billions of tiny living organisms called coral polyps.\n\nThe reef is home to thousands of different animals. You can find colorful fish, sea turtles, and even sharks living there. It is like a giant underwater city. Many people go there to swim and look at the beautiful corals through a mask.\n\nHowever, the reef is in danger because the ocean water is getting too warm. We must protect the ocean so the Great Barrier Reef can stay healthy for a long time. It is one of the most beautiful wonders of nature." 
    },
    { 
        title: "Steve Jobs and Apple", cat: "Biographies", lvl: "Easy", 
        text: "Steve Jobs was a man who changed the world of technology. He was one of the people who started the company called Apple. He was very creative and always wanted to make computers easy for everyone to use.\n\nHe helped create the first Macintosh computer, the iPod, and the iPhone. He believed that products should not only work well but also look beautiful. Because of his ideas, we now have powerful computers that we can carry in our pockets.\n\nSteve Jobs taught us that it is important to follow your heart and do what you love. He often said, 'Stay hungry, stay foolish.' Even though he is gone, his company continues to make new things that people use every day." 
    },
    { 
        title: "Why We Need Trees", cat: "Nature", lvl: "Easy", 
        text: "Trees are like the lungs of our planet. They do something very important called photosynthesis. They take in the air that we breathe out and turn it into fresh oxygen for us to breathe in.\n\nTrees also provide homes for many animals. Birds build nests in the branches, and squirrels live in the trunks. Many trees also give us delicious fruit like apples, oranges, and bananas. They also give us wood to build houses and furniture.\n\nOn a hot day, trees provide cool shade. They also help keep the ground healthy. We should plant more trees and protect our forests because we cannot live without them. Every tree is a gift to the Earth." 
    },

    // ================= MEDIUM (10 ТЕКСТОВ) =================
    { 
        title: "The Legend of Atlantis", cat: "Mythology", lvl: "Medium", 
        text: "The story of Atlantis was first told by the Greek philosopher Plato more than 2,000 years ago. According to him, Atlantis was a powerful and wealthy island nation located beyond the Pillars of Hercules. The people of Atlantis were great sailors and architects.\n\nHowever, as the people became greedy and dishonest, the gods decided to punish them. In a single day and night of misfortune, Atlantis was swallowed by the sea and disappeared forever. Since then, many people have tried to find the lost city, searching the bottom of the Atlantic Ocean.\n\nSome believe Atlantis was a real place, while others think it was just a story meant to teach a lesson about pride. Whether it existed or not, the mystery of the sunken city continues to inspire books, movies, and explorers all over the world." 
    },
    { 
        title: "The Life of Marie Curie", cat: "Biographies", lvl: "Medium", 
        text: "Marie Curie was a pioneering scientist who became the first woman to win a Nobel Prize. Born in Poland, she later moved to France to study physics and mathematics. She faced many challenges because, at that time, it was very difficult for women to go to university.\n\nWorking with her husband Pierre, she discovered two new radioactive elements: polonium and radium. Her research was dangerous, as the effects of radiation were not yet understood. Despite the risks, she dedicated her life to science and even helped develop mobile X-ray units during World War I.\n\nMarie Curie is the only person to ever win Nobel Prizes in two different sciences: Physics and Chemistry. Her discoveries paved the way for modern cancer treatments and nuclear energy. She remains an inspiration for scientists everywhere, proving that hard work and passion can change the world." 
    },
    { 
        title: "The Rise of Amazon.com", cat: "Business", lvl: "Medium", 
        text: "Amazon is now one of the largest companies in the world, but it started in a very humble way. In 1994, Jeff Bezos founded the company in his garage in Seattle. At first, Amazon only sold books online, and Bezos delivered the packages to the post office himself.\n\nBezos believed that the internet would change how people shop. He focused on 'customer obsession,' making sure that shopping was easy and deliveries were fast. Over time, Amazon began selling everything from electronics to groceries. They also created the Kindle and the Alexa voice assistant.\n\nToday, Amazon has transformed global retail and cloud computing. The company's success shows the power of long-term thinking and the importance of adapting to new technology. What started as a small online bookstore has become a 'workspace' that influences almost every part of our daily lives." 
    },
    { 
        title: "The Secrets of the Samurai", cat: "History", lvl: "Medium", 
        text: "The Samurai were the elite warrior class of ancient Japan. They were famous for their skill with the katana, a sharp and curved sword, but they were also trained in poetry, calligraphy, and tea ceremonies. Their lives were governed by a strict code of honor called Bushido.\n\nBushido, or 'the way of the warrior,' emphasized loyalty, courage, and self-discipline. A samurai was expected to be brave in battle and stoic in the face of death. They served powerful lords called Daimyo and played a major role in Japanese politics for centuries.\n\nAlthough the samurai class was abolished in the late 19th century, their influence on Japanese culture remains strong. The values of hard work and respect are still highly regarded in modern Japan. The image of the samurai continues to be a symbol of strength and integrity around the world." 
    },
    { 
        title: "How Social Media Affects the Brain", cat: "Psychology", lvl: "Medium", 
        text: "Social media has completely changed how we interact with each other. While it helps us stay connected with friends and family, psychologists are studying how it affects our mental health. One of the main issues is the 'dopamine loop' created by likes and comments.\n\nWhen we receive a notification, our brain releases dopamine, a chemical that makes us feel good. This can lead to a type of addiction where we constantly check our phones for more social approval. It can also lead to social comparison, where we feel bad because our lives don't look as perfect as the photos we see online.\n\nTo maintain a healthy relationship with technology, experts recommend 'digital detoxes' or setting limits on screen time. It is important to remember that social media is often a 'highlight reel' and not a full picture of someone's life. Focusing on real-world connections is essential for our well-being." 
    },
    { 
        title: "The Silk Road: A Bridge of Cultures", cat: "History", lvl: "Medium", 
        text: "The Silk Road was not a single road, but a vast network of trade routes that connected China to the Mediterranean Sea. For over 1,500 years, it was the main link between the East and the West. While silk was the most famous product traded, many other things traveled along these paths.\n\nSpices, paper, gunpowder, and precious stones were exchanged between different civilizations. Perhaps more importantly, the Silk Road allowed for the exchange of ideas, religions, and technologies. For example, the technique of making paper moved from China to the Islamic world and then to Europe.\n\nTraveling the Silk Road was dangerous due to deserts, mountains, and bandits. However, the profit from trade was so high that many merchants took the risk. Today, the legacy of the Silk Road is seen as the beginning of globalization, proving that trade can bring different cultures together." 
    },
    { 
        title: "Understanding Inflation", cat: "Business", lvl: "Medium", 
        text: "Have you ever noticed that a loaf of bread or a gallon of milk costs more today than it did five years ago? This general increase in prices over time is called inflation. It happens when the purchasing power of money decreases, meaning you can buy less with the same amount of cash.\n\nThere are several causes of inflation. One is 'demand-pull' inflation, which happens when people have more money to spend and want to buy more goods than companies can produce. Another is 'cost-push' inflation, which occurs when the cost of making products, like wages or raw materials, goes up.\n\nA small amount of inflation is actually considered healthy for a growing economy. However, if prices rise too quickly, it can cause problems for families who have a fixed income. Central banks try to manage inflation by changing interest rates to keep the economy stable and balanced." 
    },
    { 
        title: "The Magic of Japanese Tea Ceremony", cat: "Culture", lvl: "Medium", 
        text: "The Japanese tea ceremony, known as Chanoyu, is a traditional cultural activity involving the ceremonial preparation and presentation of matcha, a powdered green tea. It is not just about drinking tea; it is a spiritual practice focused on harmony, respect, purity, and tranquility.\n\nEvery movement in the ceremony is carefully planned and performed with grace. The host spends a long time preparing the room and choosing the right seasonal decorations. The guests must follow specific rules for entering the room, sitting, and drinking the tea. The goal is to create a moment of peace away from the busy world.\n\nThis tradition has its roots in Zen Buddhism and has been practiced for over 500 years. It reminds us to appreciate the beauty in simple things and to show respect to others. Even in modern Japan, many people still study the art of tea to find balance in their lives." 
    },
    { 
        title: "The Invention of the Printing Press", cat: "History", lvl: "Medium", 
        text: "Before the 15th century, books were copied by hand, which was a very slow and expensive process. Only the very wealthy could afford to own a book. This changed in 1440 when Johannes Gutenberg invented the printing press with movable type in Germany.\n\nHis invention allowed for the mass production of books for the first time. The first major book he printed was the Bible. As books became cheaper and more available, more people began to learn how to read and write. This led to a rapid spread of knowledge, science, and new religious ideas across Europe.\n\nThe printing press is considered one of the most important inventions in history. It fueled the Renaissance and the Scientific Revolution. Without it, the world would be a much less educated place. It was the first step toward the information age that we live in today." 
    },
    { 
        title: "The Life Cycle of a Hurricane", cat: "Geography", lvl: "Medium", 
        text: "Hurricanes are massive storm systems that form over warm ocean waters. They are like giant engines that use warm, moist air as fuel. A storm is classified as a hurricane when its wind speeds reach at least 119 kilometers per hour.\n\nA hurricane begins as a tropical disturbance. As it moves over warm water, it draws in more moisture and energy, becoming a tropical depression and then a tropical storm. The center of the hurricane is called the 'eye,' which is surprisingly calm and clear, even while the strongest winds rotate around it.\n\nWhen a hurricane hits land, it can cause heavy rain, flooding, and strong winds that destroy buildings. However, once it moves away from the warm water, it loses its power and slowly disappears. Meteorologists use satellites and planes to track these storms and warn people to stay safe." 
    },

    // ================= HARD (10 ТЕКСТОВ) =================
    { 
        title: "The Twelve Labors of Hercules", cat: "Mythology", lvl: "Hard", 
        text: "Hercules is perhaps the most iconic hero of Greek mythology, symbolizing immense strength and perseverance. However, his life was marked by tragedy. Driven to temporary madness by the goddess Hera, Hercules committed a terrible crime. To atone for his actions, he was ordered to serve King Eurystheus and perform twelve seemingly impossible tasks.\n\nThese tasks, known as the Twelve Labors, included slaying the Nemean Lion, whose skin was impervious to weapons, and cleaning the Augean stables in a single day—a feat he accomplished by rerouting two entire rivers. He also had to capture the three-headed dog Cerberus from the Underworld. Each labor required not only physical power but also strategic thinking and divine assistance.\n\nThrough these labors, Hercules transformed from a flawed man into a legendary hero. His story serves as a profound allegory for the human struggle against overwhelming odds and the possibility of redemption through hard work and suffering. Ultimately, Hercules was granted immortality among the gods on Mount Olympus." 
    },
    { 
        title: "Nikola Tesla: The Master of Lightning", cat: "Biographies", lvl: "Hard", 
        text: "Nikola Tesla was a visionary inventor whose contributions to electrical engineering fundamentally shaped the modern world. Born in modern-day Croatia, Tesla possessed an extraordinary visual memory and a mind capable of complex mathematical calculations without the need for paper. He arrived in the United States with little more than a letter of recommendation to Thomas Edison.\n\nTesla's primary legacy is the development of the alternating current (AC) system, which allowed electricity to be transmitted over vast distances. This led to a famous 'War of Currents' with Edison, who promoted direct current (DC). Tesla's vision was more efficient, and it eventually became the global standard. He also experimented with wireless communication, X-rays, and even remote control technology long before they were commercialized.\n\nDespite his brilliance, Tesla was a tragic figure who struggled with business and mental health. He died nearly penniless in a New York hotel, but his reputation has soared in recent decades. Today, he is celebrated as a genius who looked far into the future, imagining a world of free, wireless energy and interconnected communication." 
    },
    { 
        title: "The Psychology of Cognitive Dissonance", cat: "Psychology", lvl: "Hard", 
        text: "Cognitive dissonance is a psychological theory developed by Leon Festinger in 1957, describing the mental discomfort a person experiences when they hold two or more contradictory beliefs or values. This discomfort is particularly acute when a person's behavior conflicts with their deeply held self-image. Humans have an innate drive to maintain internal consistency.\n\nTo reduce this tension, individuals often engage in 'rationalization.' For example, a person who knows that smoking is unhealthy but continues to do so might convince themselves that the data is inconclusive or that the stress-relieving benefits outweigh the risks. They are not lying to others so much as they are trying to restore their own internal balance. This process often happens subconsciously, leading to biased decision-making.\n\nUnderstanding cognitive dissonance is crucial for fields like marketing, politics, and self-improvement. It explains why it is so difficult to change someone's mind with facts alone, as people will often ignore or reinterpret information that threatens their existing worldview. Recognizing our own tendency toward dissonance is the first step toward more objective and critical thinking." 
    },
    { 
        title: "The Industrial Revolution and Urbanization", cat: "History", lvl: "Hard", 
        text: "The Industrial Revolution was not merely a period of technological innovation; it was a profound social and demographic transformation. As factories replaced cottage industries, the demand for labor drew millions of people from the agrarian countryside into burgeoning industrial centers. This process, known as urbanization, completely altered the structure of human society.\n\nCities like Manchester and Chicago grew at unprecedented rates, often outpacing the development of necessary infrastructure. The result was often catastrophic for the working class: overcrowded tenements, lack of clean water, and the rapid spread of diseases like cholera. The stark contrast between the wealthy industrial magnates and the impoverished laborers led to the rise of social reform movements and the birth of modern sociology.\n\nHowever, urbanization also fostered intellectual and cultural exchange. Cities became hubs of innovation, education, and political activism. The shift from a rural to an urban population required new ways of governing and providing public services. The legacy of this era is still seen in the design of our modern mega-cities and the ongoing global trend of urban migration." 
    },
    { 
        title: "The Mechanics of Global Supply Chains", cat: "Business", lvl: "Hard", 
        text: "In the modern globalized economy, almost no product is manufactured in a single location. A smartphone, for instance, might be designed in California, use chips from Taiwan, batteries from South Korea, and be assembled in China. This intricate web of organizations, people, and resources is known as a global supply chain. Its primary goal is to maximize efficiency and minimize costs.\n\nTo manage these chains, companies use 'just-in-time' manufacturing, where components arrive at the factory exactly when they are needed. This reduces the cost of storing inventory but makes the system highly vulnerable to disruptions. A blockage in a major shipping canal, a natural disaster, or a geopolitical conflict can cause a 'bullwhip effect,' where a small delay in one part of the world leads to massive shortages elsewhere.\n\nAs the world faces new challenges like climate change and trade wars, many companies are rethinking their supply chain strategies. They are moving toward 'resilience' rather than just efficiency, which includes diversifying suppliers and bringing production closer to home. The complexity of these systems highlights how interconnected our world has become." 
    },
    { 
        title: "Quantum Entanglement: Spooky Action", cat: "Science", lvl: "Hard", 
        text: "Quantum entanglement is one of the most baffling and counterintuitive phenomena in physics. It occurs when two or more particles become linked in such a way that the quantum state of each particle cannot be described independently of the others, regardless of the distance between them. If you measure the property of one particle, you instantaneously know the state of its entangled partner.\n\nAlbert Einstein famously disliked this idea, referring to it as 'spooky action at a distance,' because it seemed to suggest that information could travel faster than the speed of light. However, numerous experiments have since proven that entanglement is a fundamental part of reality. It doesn't allow for faster-than-light communication, but it does challenge our classical notions of locality and separation.\n\nToday, entanglement is the cornerstone of the burgeoning field of quantum information science. It is the key to developing quantum computers, which use 'qubits' to perform calculations in ways that classical bits cannot. It also promises perfectly secure communication through quantum cryptography. We are moving from simply observing the quantum world to actively engineering it." 
    },
    { 
        title: "The History and Philosophy of Human Rights", cat: "History", lvl: "Hard", 
        text: "The concept of universal human rights—the idea that all people are entitled to certain fundamental protections simply by virtue of being human—is a relatively recent development in history. Its roots can be traced back to the Enlightenment, where philosophers like John Locke argued for 'natural rights' such as life, liberty, and property. These ideas fueled the American and French Revolutions.\n\nHowever, it was the atrocities of World War II that led to a formal global consensus. In 1948, the United Nations adopted the Universal Declaration of Human Rights (UDHR). This landmark document established for the first time that the international community has a responsibility to protect individuals from the abuses of their own governments. It covers civil, political, economic, and social rights.\n\nDespite the near-universal acceptance of these principles, their implementation remains a major global challenge. Cultural relativism—the argument that rights should be defined by local traditions—often conflicts with the universalist approach. The ongoing struggle for human rights is a testament to the belief that the dignity of the individual should be the highest priority of any legal system." 
    },
    { 
        title: "The Economics of Game Theory", cat: "Business", lvl: "Hard", 
        text: "Game theory is a mathematical framework used to analyze strategic interactions between rational decision-makers. It is widely applied in economics, political science, and evolutionary biology. At its core, game theory studies situations where the outcome for one participant depends not only on their own choices but also on the choices of others.\n\nA classic example is the 'Prisoner's Dilemma,' which demonstrates why two individuals might not cooperate even if it appears in their best interest to do so. In business, game theory helps companies decide on pricing strategies, whether to enter a new market, or how to bid in an auction. It assumes that players will act to maximize their own utility while anticipating the moves of their competitors.\n\nOne of the most important concepts is the 'Nash Equilibrium,' a situation where no player can benefit by changing their strategy while the other players keep theirs unchanged. Understanding these dynamics allows economists to predict market behavior and design better regulations. It reminds us that in many social and economic systems, our success is inextricably linked to the actions of others." 
    },
    { 
        title: "Genetics and the CRISPR Revolution", cat: "Science", lvl: "Hard", 
        text: "We are currently living through a biological revolution thanks to the development of CRISPR-Cas9 technology. CRISPR is a powerful tool that allows scientists to edit DNA with unprecedented precision, acting like a pair of 'molecular scissors' that can cut and replace specific genes. This technology was adapted from a natural defense mechanism found in bacteria.\n\nThe potential applications of CRISPR are staggering. It could be used to cure genetic diseases like sickle cell anemia or cystic fibrosis by correcting the mutations in a patient's cells. In agriculture, it could create crops that are resistant to drought or pests without the need for traditional pesticides. It even offers the possibility of bringing back extinct species or eliminating malaria-carrying mosquitoes.\n\nHowever, the ability to 'design' life brings profound ethical dilemmas. The prospect of 'designer babies'—where parents choose the traits of their children—raises concerns about inequality and the definition of what it means to be human. As we gain the power to rewrite the code of life, society must decide where the boundaries should be drawn." 
    },
    { 
        title: "The Philosophy of Nihilism and Meaning", cat: "Psychology", lvl: "Hard", 
        text: "Nihilism is the philosophical belief that life is without objective meaning, purpose, or intrinsic value. It often arises from a scientific worldview that sees the universe as vast, ancient, and indifferent to human concerns. While nihilism is frequently associated with despair or pessimism, many philosophers have found it to be a liberating perspective.\n\nFriedrich Nietzsche, a key figure in this area, argued that the 'death of God' and the collapse of traditional moral systems would lead to nihilism. However, he saw this as a challenge: if there is no pre-determined meaning, then humans are free to create their own values and live as 'supermen' who define their own destiny. This is often called 'optimistic nihilism.'\n\nIn modern psychology, the struggle to find meaning in an apparently meaningless world is a major theme. Existential therapy focuses on helping individuals accept this lack of inherent purpose and take responsibility for constructing their own significance through relationships, work, and creativity. It suggests that meaning is not something we 'find' in the universe, but something we 'build' within ourselves." 
    }
  // ================= EASY (10 ТЕКСТОВ) =================
    { 
        title: "The Story of King Midas", cat: "Mythology", lvl: "Easy", 
        text: "Long ago, there was a king named Midas who loved gold more than anything else in the world. One day, a god gave him a special wish. Midas wished that everything he touched would turn into shining gold.\n\nAt first, the king was very happy. He touched his flowers, his chair, and even his castle walls, and they all became gold. But then, he became hungry. When he tried to eat an apple, it turned into hard metal. When he tried to drink water, it became gold too.\n\nHe realized that his wish was actually a curse. He could not eat or drink, and he was very sad. Finally, the god took the power away. King Midas learned that there are many things in life more important than money and gold." 
    },
    { 
        title: "Albert Einstein: A Great Mind", cat: "Biographies", lvl: "Easy", 
        text: "Albert Einstein was one of the most famous scientists in history. He was born in Germany a long time ago. When he was a small boy, he did not talk much, and some people thought he was not very smart. But Albert loved to think about how the world works.\n\nHe spent a lot of time studying light and space. He discovered that time and space are connected. Because of his great ideas, he won the Nobel Prize in Physics. He became famous all over the world, but he remained a very simple and kind man.\n\nEinstein liked to play the violin and go sailing in his free time. He always encouraged children to ask questions and stay curious. His work changed science forever, and we still use his ideas today to understand the universe." 
    },
    { 
        title: "How to Start a Small Business", cat: "Business", lvl: "Easy", 
        text: "Do you want to start a business? It can be as simple as a lemonade stand or washing cars for your neighbors. First, you need an idea. Think about what people need and what you are good at doing.\n\nNext, you need a plan. You must decide how much money you need to buy supplies. For a lemonade stand, you need lemons, sugar, and cups. Then, you choose a good place to work where many people will see you.\n\nWhen you sell your product, you must be polite and smile at your customers. If you work hard and save your money, your small business can grow. Starting a business is a great way to learn about responsibility and how to handle money." 
    },
    { 
        title: "The Festival of Colors", cat: "Culture", lvl: "Easy", 
        text: "Holi is a very famous festival in India. It is often called the 'Festival of Colors'. It happens in the spring when the weather becomes warm. People celebrate the end of winter and the victory of good over evil.\n\nDuring Holi, people go out into the streets and throw colorful powder at each other. Everyone becomes red, green, blue, and yellow! They also use water balloons and spray guns to have fun. It is a time for singing, dancing, and laughing with friends.\n\nIn the evening, families visit each other and share special sweets. It is a day when everyone is equal and happy. Holi is a beautiful tradition that brings people together and fills the world with bright colors." 
    },
    { 
        title: "The Brave Firefighters", cat: "Life", lvl: "Easy", 
        text: "Firefighters are very brave people who help keep us safe. They work at a fire station and are always ready to go when the alarm rings. They wear special heavy coats, boots, and helmets to protect them from heat.\n\nWhen there is a fire, they drive a big red truck with loud sirens. They use long hoses to spray water on the flames. Firefighters also help people during car accidents and floods. They are trained to stay calm in dangerous situations.\n\nYou can visit a fire station to learn about fire safety. They will show you how to 'stop, drop, and roll' if your clothes catch fire. We should always be thankful for the hard work that firefighters do for our community." 
    },
    { 
        title: "Mount Everest: The Highest Peak", cat: "Geography", lvl: "Easy", 
        text: "Mount Everest is the highest mountain in the world. It is located in the Himalayas, between the countries of Nepal and China. It is so high that the top is always covered in snow and ice, even in the summer.\n\nClimbing Mount Everest is very difficult and dangerous. The air at the top is very thin, so climbers have to use oxygen tanks to breathe. It is also very cold, and the wind blows very hard. Many people dream of standing on the top of the world.\n\nThe first people to reach the top were Edmund Hillary and Tenzing Norgay in 1953. Today, many climbers try to follow their path. It takes a lot of training and courage to reach the highest point on Earth." 
    },
    { 
        title: "The Invention of the Telephone", cat: "Tech", lvl: "Easy", 
        text: "A long time ago, people could only send messages by letters. It took a long time for a letter to arrive. Then, a man named Alexander Graham Bell had a great idea. He wanted to send voices through wires.\n\nIn 1876, he invented the first telephone. The first words he said were, 'Mr. Watson, come here, I want to see you.' Mr. Watson was in another room and he heard Bell's voice perfectly. It was a miracle of technology!\n\nToday, we use smartphones that are much smaller and faster. We can call people on the other side of the world and even see their faces. But it all started with Bell's simple invention. The telephone changed how we talk to each other forever." 
    },
    { 
        title: "The Great Barrier Reef", cat: "Nature", lvl: "Easy", 
        text: "The Great Barrier Reef is the largest coral reef system in the world. It is located in the ocean near Australia. It is so big that you can even see it from space! It is made of billions of tiny living organisms called coral polyps.\n\nThe reef is home to thousands of different animals. You can find colorful fish, sea turtles, and even sharks living there. It is like a giant underwater city. Many people go there to swim and look at the beautiful corals through a mask.\n\nHowever, the reef is in danger because the ocean water is getting too warm. We must protect the ocean so the Great Barrier Reef can stay healthy for a long time. It is one of the most beautiful wonders of nature." 
    },
    { 
        title: "Steve Jobs and Apple", cat: "Biographies", lvl: "Easy", 
        text: "Steve Jobs was a man who changed the world of technology. He was one of the people who started the company called Apple. He was very creative and always wanted to make computers easy for everyone to use.\n\nHe helped create the first Macintosh computer, the iPod, and the iPhone. He believed that products should not only work well but also look beautiful. Because of his ideas, we now have powerful computers that we can carry in our pockets.\n\nSteve Jobs taught us that it is important to follow your heart and do what you love. He often said, 'Stay hungry, stay foolish.' Even though he is gone, his company continues to make new things that people use every day." 
    },
    { 
        title: "Why We Need Trees", cat: "Nature", lvl: "Easy", 
        text: "Trees are like the lungs of our planet. They do something very important called photosynthesis. They take in the air that we breathe out and turn it into fresh oxygen for us to breathe in.\n\nTrees also provide homes for many animals. Birds build nests in the branches, and squirrels live in the trunks. Many trees also give us delicious fruit like apples, oranges, and bananas. They also give us wood to build houses and furniture.\n\nOn a hot day, trees provide cool shade. They also help keep the ground healthy. We should plant more trees and protect our forests because we cannot live without them. Every tree is a gift to the Earth." 
    },

    // ================= MEDIUM (10 ТЕКСТОВ) =================
    { 
        title: "The Legend of Atlantis", cat: "Mythology", lvl: "Medium", 
        text: "The story of Atlantis was first told by the Greek philosopher Plato more than 2,000 years ago. According to him, Atlantis was a powerful and wealthy island nation located beyond the Pillars of Hercules. The people of Atlantis were great sailors and architects.\n\nHowever, as the people became greedy and dishonest, the gods decided to punish them. In a single day and night of misfortune, Atlantis was swallowed by the sea and disappeared forever. Since then, many people have tried to find the lost city, searching the bottom of the Atlantic Ocean.\n\nSome believe Atlantis was a real place, while others think it was just a story meant to teach a lesson about pride. Whether it existed or not, the mystery of the sunken city continues to inspire books, movies, and explorers all over the world." 
    },
    { 
        title: "The Life of Marie Curie", cat: "Biographies", lvl: "Medium", 
        text: "Marie Curie was a pioneering scientist who became the first woman to win a Nobel Prize. Born in Poland, she later moved to France to study physics and mathematics. She faced many challenges because, at that time, it was very difficult for women to go to university.\n\nWorking with her husband Pierre, she discovered two new radioactive elements: polonium and radium. Her research was dangerous, as the effects of radiation were not yet understood. Despite the risks, she dedicated her life to science and even helped develop mobile X-ray units during World War I.\n\nMarie Curie is the only person to ever win Nobel Prizes in two different sciences: Physics and Chemistry. Her discoveries paved the way for modern cancer treatments and nuclear energy. She remains an inspiration for scientists everywhere, proving that hard work and passion can change the world." 
    },
    { 
        title: "The Rise of Amazon.com", cat: "Business", lvl: "Medium", 
        text: "Amazon is now one of the largest companies in the world, but it started in a very humble way. In 1994, Jeff Bezos founded the company in his garage in Seattle. At first, Amazon only sold books online, and Bezos delivered the packages to the post office himself.\n\nBezos believed that the internet would change how people shop. He focused on 'customer obsession,' making sure that shopping was easy and deliveries were fast. Over time, Amazon began selling everything from electronics to groceries. They also created the Kindle and the Alexa voice assistant.\n\nToday, Amazon has transformed global retail and cloud computing. The company's success shows the power of long-term thinking and the importance of adapting to new technology. What started as a small online bookstore has become a 'workspace' that influences almost every part of our daily lives." 
    },
    { 
        title: "The Secrets of the Samurai", cat: "History", lvl: "Medium", 
        text: "The Samurai were the elite warrior class of ancient Japan. They were famous for their skill with the katana, a sharp and curved sword, but they were also trained in poetry, calligraphy, and tea ceremonies. Their lives were governed by a strict code of honor called Bushido.\n\nBushido, or 'the way of the warrior,' emphasized loyalty, courage, and self-discipline. A samurai was expected to be brave in battle and stoic in the face of death. They served powerful lords called Daimyo and played a major role in Japanese politics for centuries.\n\nAlthough the samurai class was abolished in the late 19th century, their influence on Japanese culture remains strong. The values of hard work and respect are still highly regarded in modern Japan. The image of the samurai continues to be a symbol of strength and integrity around the world." 
    },
    { 
        title: "How Social Media Affects the Brain", cat: "Psychology", lvl: "Medium", 
        text: "Social media has completely changed how we interact with each other. While it helps us stay connected with friends and family, psychologists are studying how it affects our mental health. One of the main issues is the 'dopamine loop' created by likes and comments.\n\nWhen we receive a notification, our brain releases dopamine, a chemical that makes us feel good. This can lead to a type of addiction where we constantly check our phones for more social approval. It can also lead to social comparison, where we feel bad because our lives don't look as perfect as the photos we see online.\n\nTo maintain a healthy relationship with technology, experts recommend 'digital detoxes' or setting limits on screen time. It is important to remember that social media is often a 'highlight reel' and not a full picture of someone's life. Focusing on real-world connections is essential for our well-being." 
    },
    { 
        title: "The Silk Road: A Bridge of Cultures", cat: "History", lvl: "Medium", 
        text: "The Silk Road was not a single road, but a vast network of trade routes that connected China to the Mediterranean Sea. For over 1,500 years, it was the main link between the East and the West. While silk was the most famous product traded, many other things traveled along these paths.\n\nSpices, paper, gunpowder, and precious stones were exchanged between different civilizations. Perhaps more importantly, the Silk Road allowed for the exchange of ideas, religions, and technologies. For example, the technique of making paper moved from China to the Islamic world and then to Europe.\n\nTraveling the Silk Road was dangerous due to deserts, mountains, and bandits. However, the profit from trade was so high that many merchants took the risk. Today, the legacy of the Silk Road is seen as the beginning of globalization, proving that trade can bring different cultures together." 
    },
    { 
        title: "Understanding Inflation", cat: "Business", lvl: "Medium", 
        text: "Have you ever noticed that a loaf of bread or a gallon of milk costs more today than it did five years ago? This general increase in prices over time is called inflation. It happens when the purchasing power of money decreases, meaning you can buy less with the same amount of cash.\n\nThere are several causes of inflation. One is 'demand-pull' inflation, which happens when people have more money to spend and want to buy more goods than companies can produce. Another is 'cost-push' inflation, which occurs when the cost of making products, like wages or raw materials, goes up.\n\nA small amount of inflation is actually considered healthy for a growing economy. However, if prices rise too quickly, it can cause problems for families who have a fixed income. Central banks try to manage inflation by changing interest rates to keep the economy stable and balanced." 
    },
    { 
        title: "The Magic of Japanese Tea Ceremony", cat: "Culture", lvl: "Medium", 
        text: "The Japanese tea ceremony, known as Chanoyu, is a traditional cultural activity involving the ceremonial preparation and presentation of matcha, a powdered green tea. It is not just about drinking tea; it is a spiritual practice focused on harmony, respect, purity, and tranquility.\n\nEvery movement in the ceremony is carefully planned and performed with grace. The host spends a long time preparing the room and choosing the right seasonal decorations. The guests must follow specific rules for entering the room, sitting, and drinking the tea. The goal is to create a moment of peace away from the busy world.\n\nThis tradition has its roots in Zen Buddhism and has been practiced for over 500 years. It reminds us to appreciate the beauty in simple things and to show respect to others. Even in modern Japan, many people still study the art of tea to find balance in their lives." 
    },
    { 
        title: "The Invention of the Printing Press", cat: "History", lvl: "Medium", 
        text: "Before the 15th century, books were copied by hand, which was a very slow and expensive process. Only the very wealthy could afford to own a book. This changed in 1440 when Johannes Gutenberg invented the printing press with movable type in Germany.\n\nHis invention allowed for the mass production of books for the first time. The first major book he printed was the Bible. As books became cheaper and more available, more people began to learn how to read and write. This led to a rapid spread of knowledge, science, and new religious ideas across Europe.\n\nThe printing press is considered one of the most important inventions in history. It fueled the Renaissance and the Scientific Revolution. Without it, the world would be a much less educated place. It was the first step toward the information age that we live in today." 
    },
    { 
        title: "The Life Cycle of a Hurricane", cat: "Geography", lvl: "Medium", 
        text: "Hurricanes are massive storm systems that form over warm ocean waters. They are like giant engines that use warm, moist air as fuel. A storm is classified as a hurricane when its wind speeds reach at least 119 kilometers per hour.\n\nA hurricane begins as a tropical disturbance. As it moves over warm water, it draws in more moisture and energy, becoming a tropical depression and then a tropical storm. The center of the hurricane is called the 'eye,' which is surprisingly calm and clear, even while the strongest winds rotate around it.\n\nWhen a hurricane hits land, it can cause heavy rain, flooding, and strong winds that destroy buildings. However, once it moves away from the warm water, it loses its power and slowly disappears. Meteorologists use satellites and planes to track these storms and warn people to stay safe." 
    },

    // ================= HARD (10 ТЕКСТОВ) =================
    { 
        title: "The Twelve Labors of Hercules", cat: "Mythology", lvl: "Hard", 
        text: "Hercules is perhaps the most iconic hero of Greek mythology, symbolizing immense strength and perseverance. However, his life was marked by tragedy. Driven to temporary madness by the goddess Hera, Hercules committed a terrible crime. To atone for his actions, he was ordered to serve King Eurystheus and perform twelve seemingly impossible tasks.\n\nThese tasks, known as the Twelve Labors, included slaying the Nemean Lion, whose skin was impervious to weapons, and cleaning the Augean stables in a single day—a feat he accomplished by rerouting two entire rivers. He also had to capture the three-headed dog Cerberus from the Underworld. Each labor required not only physical power but also strategic thinking and divine assistance.\n\nThrough these labors, Hercules transformed from a flawed man into a legendary hero. His story serves as a profound allegory for the human struggle against overwhelming odds and the possibility of redemption through hard work and suffering. Ultimately, Hercules was granted immortality among the gods on Mount Olympus." 
    },
    { 
        title: "Nikola Tesla: The Master of Lightning", cat: "Biographies", lvl: "Hard", 
        text: "Nikola Tesla was a visionary inventor whose contributions to electrical engineering fundamentally shaped the modern world. Born in modern-day Croatia, Tesla possessed an extraordinary visual memory and a mind capable of complex mathematical calculations without the need for paper. He arrived in the United States with little more than a letter of recommendation to Thomas Edison.\n\nTesla's primary legacy is the development of the alternating current (AC) system, which allowed electricity to be transmitted over vast distances. This led to a famous 'War of Currents' with Edison, who promoted direct current (DC). Tesla's vision was more efficient, and it eventually became the global standard. He also experimented with wireless communication, X-rays, and even remote control technology long before they were commercialized.\n\nDespite his brilliance, Tesla was a tragic figure who struggled with business and mental health. He died nearly penniless in a New York hotel, but his reputation has soared in recent decades. Today, he is celebrated as a genius who looked far into the future, imagining a world of free, wireless energy and interconnected communication." 
    },
    { 
        title: "The Psychology of Cognitive Dissonance", cat: "Psychology", lvl: "Hard", 
        text: "Cognitive dissonance is a psychological theory developed by Leon Festinger in 1957, describing the mental discomfort a person experiences when they hold two or more contradictory beliefs or values. This discomfort is particularly acute when a person's behavior conflicts with their deeply held self-image. Humans have an innate drive to maintain internal consistency.\n\nTo reduce this tension, individuals often engage in 'rationalization.' For example, a person who knows that smoking is unhealthy but continues to do so might convince themselves that the data is inconclusive or that the stress-relieving benefits outweigh the risks. They are not lying to others so much as they are trying to restore their own internal balance. This process often happens subconsciously, leading to biased decision-making.\n\nUnderstanding cognitive dissonance is crucial for fields like marketing, politics, and self-improvement. It explains why it is so difficult to change someone's mind with facts alone, as people will often ignore or reinterpret information that threatens their existing worldview. Recognizing our own tendency toward dissonance is the first step toward more objective and critical thinking." 
    },
    { 
        title: "The Industrial Revolution and Urbanization", cat: "History", lvl: "Hard", 
        text: "The Industrial Revolution was not merely a period of technological innovation; it was a profound social and demographic transformation. As factories replaced cottage industries, the demand for labor drew millions of people from the agrarian countryside into burgeoning industrial centers. This process, known as urbanization, completely altered the structure of human society.\n\nCities like Manchester and Chicago grew at unprecedented rates, often outpacing the development of necessary infrastructure. The result was often catastrophic for the working class: overcrowded tenements, lack of clean water, and the rapid spread of diseases like cholera. The stark contrast between the wealthy industrial magnates and the impoverished laborers led to the rise of social reform movements and the birth of modern sociology.\n\nHowever, urbanization also fostered intellectual and cultural exchange. Cities became hubs of innovation, education, and political activism. The shift from a rural to an urban population required new ways of governing and providing public services. The legacy of this era is still seen in the design of our modern mega-cities and the ongoing global trend of urban migration." 
    },
    { 
        title: "The Mechanics of Global Supply Chains", cat: "Business", lvl: "Hard", 
        text: "In the modern globalized economy, almost no product is manufactured in a single location. A smartphone, for instance, might be designed in California, use chips from Taiwan, batteries from South Korea, and be assembled in China. This intricate web of organizations, people, and resources is known as a global supply chain. Its primary goal is to maximize efficiency and minimize costs.\n\nTo manage these chains, companies use 'just-in-time' manufacturing, where components arrive at the factory exactly when they are needed. This reduces the cost of storing inventory but makes the system highly vulnerable to disruptions. A blockage in a major shipping canal, a natural disaster, or a geopolitical conflict can cause a 'bullwhip effect,' where a small delay in one part of the world leads to massive shortages elsewhere.\n\nAs the world faces new challenges like climate change and trade wars, many companies are rethinking their supply chain strategies. They are moving toward 'resilience' rather than just efficiency, which includes diversifying suppliers and bringing production closer to home. The complexity of these systems highlights how interconnected our world has become." 
    },
    { 
        title: "Quantum Entanglement: Spooky Action", cat: "Science", lvl: "Hard", 
        text: "Quantum entanglement is one of the most baffling and counterintuitive phenomena in physics. It occurs when two or more particles become linked in such a way that the quantum state of each particle cannot be described independently of the others, regardless of the distance between them. If you measure the property of one particle, you instantaneously know the state of its entangled partner.\n\nAlbert Einstein famously disliked this idea, referring to it as 'spooky action at a distance,' because it seemed to suggest that information could travel faster than the speed of light. However, numerous experiments have since proven that entanglement is a fundamental part of reality. It doesn't allow for faster-than-light communication, but it does challenge our classical notions of locality and separation.\n\nToday, entanglement is the cornerstone of the burgeoning field of quantum information science. It is the key to developing quantum computers, which use 'qubits' to perform calculations in ways that classical bits cannot. It also promises perfectly secure communication through quantum cryptography. We are moving from simply observing the quantum world to actively engineering it." 
    },
    { 
        title: "The History and Philosophy of Human Rights", cat: "History", lvl: "Hard", 
        text: "The concept of universal human rights—the idea that all people are entitled to certain fundamental protections simply by virtue of being human—is a relatively recent development in history. Its roots can be traced back to the Enlightenment, where philosophers like John Locke argued for 'natural rights' such as life, liberty, and property. These ideas fueled the American and French Revolutions.\n\nHowever, it was the atrocities of World War II that led to a formal global consensus. In 1948, the United Nations adopted the Universal Declaration of Human Rights (UDHR). This landmark document established for the first time that the international community has a responsibility to protect individuals from the abuses of their own governments. It covers civil, political, economic, and social rights.\n\nDespite the near-universal acceptance of these principles, their implementation remains a major global challenge. Cultural relativism—the argument that rights should be defined by local traditions—often conflicts with the universalist approach. The ongoing struggle for human rights is a testament to the belief that the dignity of the individual should be the highest priority of any legal system." 
    },
    { 
        title: "The Economics of Game Theory", cat: "Business", lvl: "Hard", 
        text: "Game theory is a mathematical framework used to analyze strategic interactions between rational decision-makers. It is widely applied in economics, political science, and evolutionary biology. At its core, game theory studies situations where the outcome for one participant depends not only on their own choices but also on the choices of others.\n\nA classic example is the 'Prisoner's Dilemma,' which demonstrates why two individuals might not cooperate even if it appears in their best interest to do so. In business, game theory helps companies decide on pricing strategies, whether to enter a new market, or how to bid in an auction. It assumes that players will act to maximize their own utility while anticipating the moves of their competitors.\n\nOne of the most important concepts is the 'Nash Equilibrium,' a situation where no player can benefit by changing their strategy while the other players keep theirs unchanged. Understanding these dynamics allows economists to predict market behavior and design better regulations. It reminds us that in many social and economic systems, our success is inextricably linked to the actions of others." 
    },
    { 
        title: "Genetics and the CRISPR Revolution", cat: "Science", lvl: "Hard", 
        text: "We are currently living through a biological revolution thanks to the development of CRISPR-Cas9 technology. CRISPR is a powerful tool that allows scientists to edit DNA with unprecedented precision, acting like a pair of 'molecular scissors' that can cut and replace specific genes. This technology was adapted from a natural defense mechanism found in bacteria.\n\nThe potential applications of CRISPR are staggering. It could be used to cure genetic diseases like sickle cell anemia or cystic fibrosis by correcting the mutations in a patient's cells. In agriculture, it could create crops that are resistant to drought or pests without the need for traditional pesticides. It even offers the possibility of bringing back extinct species or eliminating malaria-carrying mosquitoes.\n\nHowever, the ability to 'design' life brings profound ethical dilemmas. The prospect of 'designer babies'—where parents choose the traits of their children—raises concerns about inequality and the definition of what it means to be human. As we gain the power to rewrite the code of life, society must decide where the boundaries should be drawn." 
    },
    { 
        title: "The Philosophy of Nihilism and Meaning", cat: "Psychology", lvl: "Hard", 
        text: "Nihilism is the philosophical belief that life is without objective meaning, purpose, or intrinsic value. It often arises from a scientific worldview that sees the universe as vast, ancient, and indifferent to human concerns. While nihilism is frequently associated with despair or pessimism, many philosophers have found it to be a liberating perspective.\n\nFriedrich Nietzsche, a key figure in this area, argued that the 'death of God' and the collapse of traditional moral systems would lead to nihilism. However, he saw this as a challenge: if there is no pre-determined meaning, then humans are free to create their own values and live as 'supermen' who define their own destiny. This is often called 'optimistic nihilism.'\n\nIn modern psychology, the struggle to find meaning in an apparently meaningless world is a major theme. Existential therapy focuses on helping individuals accept this lack of inherent purpose and take responsibility for constructing their own significance through relationships, work, and creativity. It suggests that meaning is not something we 'find' in the universe, but something we 'build' within ourselves." 
    }
];

